import DICOMKit
import Foundation

/// An asynchronous byte-transport for complete DICOM Upper Layer PDUs.
///
/// Implement this protocol with Network.framework, a TLS stream, or a test
/// double. The association actor owns protocol ordering; transports only move
/// complete PDUs.
public protocol DICOMULTransport: Sendable {
    func send(_ pdu: DICOMULPDU) async throws
    func receive() async throws -> DICOMULPDU
    /// Must unblock any `receive()` currently in flight, for example by causing it to
    /// throw. This is required even when the underlying primitive does not itself react
    /// to `Task` cancellation, since ``DICOMAssociation`` relies on `close()` — not
    /// cancellation — to free a `receive()` blocked past ``DICOMAssociation``'s
    /// response timeout. `NetworkDICOMULTransport.close()` satisfies this via
    /// `NWConnection.cancel()`.
    func close() async
}

/// Errors generated by the DICOM association state machine.
public enum DICOMAssociationError: Error, Sendable, Equatable {
    case notAssociated
    case rejected(DICOMAssociationRejection)
    case unexpectedPDU
    case unexpectedDIMSECommand
    case timedOut
    case aborted(source: UInt8, reason: UInt8)
    case releasedByPeer
    /// A dataset passed to ``DICOMAssociation/cStore(messageID:file:)`` is missing
    /// SOP Class UID `(0008,0016)` or SOP Instance UID `(0008,0018)`.
    case missingSOPInstanceIdentification
    /// `updatePerformedProcedureStep(messageID:contextID:sopInstanceUID:status:attributes:transferSyntax:)`
    /// was asked to move a Modality Performed Procedure Step to `.inProgress`,
    /// which N-SET may never do — a step only enters `IN PROGRESS` once, via N-CREATE.
    case invalidProcedureStepTransition
}

/// The final status and identifier datasets returned by a C-FIND operation.
public struct DICOMCFindResult: Sendable, Equatable {
    public let status: DICOMDIMSEStatus
    public let identifiers: [Data]
    public init(status: DICOMDIMSEStatus, identifiers: [Data]) { self.status = status; self.identifiers = identifiers }
}

/// The final status, sub-operation progress, and error comment returned by a C-MOVE operation.
public struct DICOMCMoveResult: Sendable, Equatable {
    public let status: DICOMDIMSEStatus
    public let subOperations: DICOMSubOperationCounts?
    public let errorComment: String?
    public init(status: DICOMDIMSEStatus, subOperations: DICOMSubOperationCounts?, errorComment: String?) {
        self.status = status; self.subOperations = subOperations; self.errorComment = errorComment
    }
}

/// The final status, sub-operation progress, and error comment returned by a C-GET operation.
public struct DICOMCGetResult: Sendable, Equatable {
    public let status: DICOMDIMSEStatus
    public let subOperations: DICOMSubOperationCounts?
    public let errorComment: String?
    public init(status: DICOMDIMSEStatus, subOperations: DICOMSubOperationCounts?, errorComment: String?) {
        self.status = status; self.subOperations = subOperations; self.errorComment = errorComment
    }
}

/// A DIMSE request received by an SCP through ``DICOMAssociation/receiveRequest()``.
public struct DICOMDIMSERequest: Sendable, Equatable {
    public let command: DICOMDIMSECommand
    public let contextID: UInt8
    public let dataset: Data?
    public init(command: DICOMDIMSECommand, contextID: UInt8, dataset: Data?) {
        self.command = command; self.contextID = contextID; self.dataset = dataset
    }
}

/// The result of a DIMSE-N (Normalized) service operation: the peer's final
/// status, the Affected SOP Class/Instance UID it reported, and the
/// Attribute List, Action Reply, or Event Reply data set it returned — `nil`
/// when the response declared none.
public struct DICOMNServiceResult: Sendable, Equatable {
    public let status: DICOMDIMSEStatus
    public let affectedSOPClassUID: String?
    public let affectedSOPInstanceUID: String?
    public let dataset: Data?
    public init(status: DICOMDIMSEStatus, affectedSOPClassUID: String?, affectedSOPInstanceUID: String?, dataset: Data?) {
        self.status = status; self.affectedSOPClassUID = affectedSOPClassUID; self.affectedSOPInstanceUID = affectedSOPInstanceUID; self.dataset = dataset
    }
}

/// An incoming C-STORE request awaiting an SCP response.
public struct DICOMCStoreRequest: Sendable, Equatable {
    public let messageID: UInt16
    public let contextID: UInt8
    public let sopClassUID: String
    public let sopInstanceUID: String
    public let dataset: Data
    public init(messageID: UInt16, contextID: UInt8, sopClassUID: String, sopInstanceUID: String, dataset: Data) {
        self.messageID = messageID; self.contextID = contextID; self.sopClassUID = sopClassUID; self.sopInstanceUID = sopInstanceUID; self.dataset = dataset
    }
}

/// A serial DICOM SCU association built on a caller-supplied PDU transport.
public actor DICOMAssociation {
    private let transport: any DICOMULTransport
    private let responseTimeout: Duration?
    private var acceptance: DICOMAssociationAcceptance?
    private var requestedPresentationContexts: [DICOMPresentationContext] = []

    /// Creates an association. A non-`nil` timeout applies to every peer PDU
    /// awaited by this actor, including association negotiation and DIMSE responses.
    public init(transport: any DICOMULTransport, responseTimeout: Duration? = nil) {
        self.transport = transport
        self.responseTimeout = responseTimeout
    }

    /// Sends A-ASSOCIATE-RQ and waits for acceptance or rejection.
    @discardableResult
    public func request(_ request: DICOMAssociationRequest) async throws -> DICOMAssociationAcceptance {
        guard acceptance == nil else { throw DICOMAssociationError.unexpectedPDU }
        requestedPresentationContexts = request.presentationContexts
        try await transport.send(.associationRequest(request))
        switch try await receivePDU() {
        case .associationAcceptance(let result): acceptance = result; return result
        case .associationRejection(let rejection): throw DICOMAssociationError.rejected(rejection)
        default: throw DICOMAssociationError.unexpectedPDU
        }
    }

    /// Waits for the peer's A-ASSOCIATE-RQ. Pass the result to ``accept(_:policy:)``
    /// to negotiate and respond. Throws ``DICOMAssociationError/unexpectedPDU`` if
    /// this association is already established or the peer sends any other PDU.
    public func receiveAssociationRequest() async throws -> DICOMAssociationRequest {
        guard acceptance == nil else { throw DICOMAssociationError.unexpectedPDU }
        guard case .associationRequest(let request) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
        return request
    }

    /// Negotiates `request` against `policy` and sends the resulting A-ASSOCIATE-AC
    /// or A-ASSOCIATE-RJ. On acceptance, records the association state so that
    /// ``receiveRequest()``, the `respondTo…` helpers, ``presentationContextID(for:)``,
    /// and ``negotiatedRoles(for:)`` behave as they do for an SCU. On rejection, closes
    /// the transport and throws ``DICOMAssociationError/rejected(_:)`` with the
    /// rejection that was sent.
    @discardableResult
    public func accept(_ request: DICOMAssociationRequest, policy: DICOMAssociationPolicy) async throws -> DICOMAssociationAcceptance {
        switch policy.negotiate(request) {
        case .accept(let result):
            requestedPresentationContexts = request.presentationContexts
            do {
                try await transport.send(.associationAcceptance(result))
            } catch {
                await transport.close()
                throw error
            }
            acceptance = result
            return result
        case .reject(let rejection):
            do {
                try await transport.send(.associationRejection(rejection))
            } catch {
                await transport.close()
                throw error
            }
            await transport.close()
            throw DICOMAssociationError.rejected(rejection)
        }
    }

    /// Returns the negotiated presentation-context ID for an abstract syntax
    /// (normally a SOP Class UID), or `nil` when it was not accepted.
    public func presentationContextID(for abstractSyntaxUID: String) -> UInt8? {
        guard let acceptance else { return nil }
        return requestedPresentationContexts.first { requested in
            requested.abstractSyntaxUID == abstractSyntaxUID && acceptance.presentationContexts.contains { accepted in
                accepted.id == requested.id && accepted.result == .acceptance
            }
        }?.id
    }

    /// Performs a C-ECHO request and returns the DIMSE status code.
    public func cEcho(messageID: UInt16, contextID: UInt8) async throws -> DICOMDIMSEStatus {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let values = try DICOMDIMSECommand.cEchoRequest(messageID: messageID).commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)
        try await transport.send(.pData(values))
        var command = Data()
        while true {
            guard case .pData(let received) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in received where value.contextID == contextID && value.isCommand {
                command.append(value.data)
                if value.isLastFragment {
                    guard case .cEchoResponse(let responseID, let status) = try DICOMDIMSECommand.decodeCommandSet(command), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    return status
                }
            }
        }
    }

    /// Sends a C-STORE request and its dataset using the negotiated presentation context.
    /// The dataset must already use that context's negotiated transfer syntax and excludes
    /// the Part 10 File Meta Information.
    public func cStore(messageID: UInt16, contextID: UInt8, sopClassUID: String, sopInstanceUID: String, dataset: Data) async throws -> DICOMDIMSEStatus {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.cStoreRequest(messageID: messageID, affectedSOPClassUID: sopClassUID, affectedSOPInstanceUID: sopInstanceUID)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        let dataValues = pdvs(data: dataset, contextID: contextID, maximumPayloadLength: maximumPayload)
        try await transport.send(.pData(dataValues))
        var response = Data()
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID && value.isCommand {
                response.append(value.data)
                if value.isLastFragment {
                    guard case .cStoreResponse(let responseID, let status) = try DICOMDIMSECommand.decodeCommandSet(response), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    return status
                }
            }
        }
    }

    /// Sends C-STORE using the accepted presentation context for `sopClassUID`.
    public func cStore(messageID: UInt16, sopClassUID: String, sopInstanceUID: String, dataset: Data) async throws -> DICOMDIMSEStatus {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await cStore(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, sopInstanceUID: sopInstanceUID, dataset: dataset)
    }

    /// Sends C-STORE for `file`, using the accepted presentation context for its
    /// SOP Class UID `(0008,0016)` and encoding its dataset in that context's
    /// negotiated transfer syntax. Throws ``DICOMAssociationError/missingSOPInstanceIdentification``
    /// if the dataset lacks SOP Class UID or SOP Instance UID `(0008,0018)`, and
    /// ``DICOMAssociationError/notAssociated`` if no context was accepted for the SOP Class.
    public func cStore(messageID: UInt16, file: DICOMFile) async throws -> DICOMDIMSEStatus {
        guard let sopClassUID = file.dataset[.sopClassUID]?.stringValue,
              let sopInstanceUID = file.dataset[.sopInstanceUID]?.stringValue else {
            throw DICOMAssociationError.missingSOPInstanceIdentification
        }
        guard let contextID = presentationContextID(for: sopClassUID),
              let negotiatedTransferSyntaxUID = acceptance?.presentationContexts.first(where: { $0.id == contextID })?.transferSyntaxUID else {
            throw DICOMAssociationError.notAssociated
        }
        let dataset = try file.encodedDatasetData(transferSyntax: TransferSyntax(uid: negotiatedTransferSyntaxUID))
        return try await cStore(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, sopInstanceUID: sopInstanceUID, dataset: dataset)
    }

    /// Performs C-FIND, collecting identifier datasets for every pending response.
    public func cFind(messageID: UInt16, contextID: UInt8, sopClassUID: String, identifier: Data) async throws -> DICOMCFindResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        try await transport.send(.pData(try DICOMDIMSECommand.cFindRequest(messageID: messageID, affectedSOPClassUID: sopClassUID).commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload)))
        var identifiers: [Data] = []
        var responseCommand = Data()
        var identifierBuffer = Data()
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID {
                if value.isCommand {
                    responseCommand.append(value.data)
                    guard value.isLastFragment else { continue }
                    guard case .cFindResponse(let responseID, let status, _, _) = try DICOMDIMSECommand.decodeCommandSet(responseCommand), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    responseCommand.removeAll(keepingCapacity: true)
                    if !status.isPending { return DICOMCFindResult(status: status, identifiers: identifiers) }
                } else {
                    // Each pending response includes one identifier dataset, possibly split
                    // across several PDVs; only the last carries isLastFragment. A production
                    // SCP sends the command PDU before this dataset PDU.
                    identifierBuffer.append(value.data)
                    guard value.isLastFragment else { continue }
                    identifiers.append(identifierBuffer)
                    identifierBuffer.removeAll(keepingCapacity: true)
                }
            }
        }
    }

    /// Performs C-FIND using the accepted presentation context for `sopClassUID`.
    public func cFind(messageID: UInt16, sopClassUID: String, identifier: Data) async throws -> DICOMCFindResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await cFind(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, identifier: identifier)
    }

    /// Performs C-MOVE and returns its final DIMSE status. Pending progress
    /// responses are consumed until the peer emits a final response.
    public func cMove(messageID: UInt16, contextID: UInt8, sopClassUID: String, destination: String, identifier: Data) async throws -> DICOMCMoveResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.cMoveRequest(messageID: messageID, affectedSOPClassUID: sopClassUID, moveDestination: destination)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload)))
        var response = Data()
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID && value.isCommand {
                response.append(value.data)
                guard value.isLastFragment else { continue }
                guard case .cMoveResponse(let responseID, let status, _, let subOperations, let errorComment) = try DICOMDIMSECommand.decodeCommandSet(response), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                response.removeAll(keepingCapacity: true)
                if !status.isPending { return DICOMCMoveResult(status: status, subOperations: subOperations, errorComment: errorComment) }
            }
        }
    }

    /// Performs C-MOVE using the accepted presentation context for `sopClassUID`.
    public func cMove(messageID: UInt16, sopClassUID: String, destination: String, identifier: Data) async throws -> DICOMCMoveResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await cMove(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, destination: destination, identifier: identifier)
    }

    /// Returns the accepted SCP/SCU role selection for `sopClassUID` from the
    /// A-ASSOCIATE-AC, or `nil` when the peer did not negotiate one.
    public func negotiatedRoles(for sopClassUID: String) -> DICOMRoleSelection? {
        acceptance?.roleSelections.first { $0.sopClassUID == sopClassUID }
    }

    /// Performs C-GET and returns the final DIMSE status with its sub-operation counts.
    ///
    /// Per PS3.4 C.4.3 the peer returns each matching instance as a C-STORE
    /// sub-operation on a storage presentation context, interleaved with pending
    /// C-GET responses on this context, so the caller must negotiate a storage
    /// presentation context for every SOP Class it expects to receive. Per PS3.7
    /// Annex D.3.3.4 it must also propose an SCP role in SCP/SCU role selection
    /// negotiation for each of those SOP Classes.
    ///
    /// `onStore` receives every retrieved instance and returns the DIMSE status sent
    /// back to the peer in the C-STORE-RSP. It is awaited inside this actor, so it
    /// must not call back into this same ``DICOMAssociation``.
    public func cGet(
        messageID: UInt16,
        contextID: UInt8,
        sopClassUID: String,
        identifier: Data,
        onStore: @Sendable (DICOMCStoreRequest) async -> DICOMDIMSEStatus
    ) async throws -> DICOMCGetResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        try await transport.send(.pData(try DICOMDIMSECommand.cGetRequest(messageID: messageID, affectedSOPClassUID: sopClassUID).commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload)))
        var response = Data()
        var subCommands: [UInt8: Data] = [:]
        var pendingStore: (messageID: UInt16, sopClassUID: String, sopInstanceUID: String, contextID: UInt8)?
        var subDataset = Data()
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values {
                if value.contextID == contextID, value.isCommand {
                    response.append(value.data)
                    guard value.isLastFragment else { continue }
                    guard case .cGetResponse(let responseID, let status, _, let subOperations, let errorComment) = try DICOMDIMSECommand.decodeCommandSet(response), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    response.removeAll(keepingCapacity: true)
                    if !status.isPending { return DICOMCGetResult(status: status, subOperations: subOperations, errorComment: errorComment) }
                } else if value.isCommand {
                    subCommands[value.contextID, default: Data()].append(value.data)
                    guard value.isLastFragment, let command = subCommands.removeValue(forKey: value.contextID) else { continue }
                    guard case .cStoreRequest(let storeID, let storeClassUID, let storeInstanceUID) = try DICOMDIMSECommand.decodeCommandSet(command) else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    pendingStore = (storeID, storeClassUID, storeInstanceUID, value.contextID)
                    subDataset.removeAll(keepingCapacity: true)
                } else if let store = pendingStore, value.contextID == store.contextID {
                    subDataset.append(value.data)
                    guard value.isLastFragment else { continue }
                    let request = DICOMCStoreRequest(messageID: store.messageID, contextID: store.contextID, sopClassUID: store.sopClassUID, sopInstanceUID: store.sopInstanceUID, dataset: subDataset)
                    let status = await onStore(request)
                    try await respond(to: request, status: status)
                    pendingStore = nil
                    subDataset.removeAll(keepingCapacity: true)
                }
                // Any remaining data PDV is the C-GET response's optional failed-SOP-
                // instance-UID-list identifier, which this API does not surface.
            }
        }
    }

    /// Performs C-GET using the accepted presentation context for `sopClassUID`.
    public func cGet(
        messageID: UInt16,
        sopClassUID: String,
        identifier: Data,
        onStore: @Sendable (DICOMCStoreRequest) async -> DICOMDIMSEStatus
    ) async throws -> DICOMCGetResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await cGet(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, identifier: identifier, onStore: onStore)
    }

    // MARK: - N-service SCU operations

    /// Sends N-CREATE, asking the peer to create a new Normalized SOP Instance.
    /// `sopInstanceUID` may be `nil` to let the peer assign one.
    public func nCreate(messageID: UInt16, contextID: UInt8, sopClassUID: String, sopInstanceUID: String?, attributes: Data?) async throws -> DICOMNServiceResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.nCreateRequest(messageID: messageID, affectedSOPClassUID: sopClassUID, affectedSOPInstanceUID: sopInstanceUID, datasetFollows: attributes != nil)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let attributes { try await transport.send(.pData(pdvs(data: attributes, contextID: contextID, maximumPayloadLength: maximumPayload))) }
        let decoded = try DICOMDIMSECommand.decodeCommandSet(try await receiveCommand(contextID: contextID))
        guard case .nCreateResponse(let responseID, let sopClassUID, let sopInstanceUID, let status, _) = decoded, responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
        let dataset = decoded.hasDataset ? try await receiveDataset(contextID: contextID) : nil
        return DICOMNServiceResult(status: status, affectedSOPClassUID: sopClassUID, affectedSOPInstanceUID: sopInstanceUID, dataset: dataset)
    }

    /// Sends N-CREATE using the accepted presentation context for `sopClassUID`.
    public func nCreate(messageID: UInt16, sopClassUID: String, sopInstanceUID: String?, attributes: Data?) async throws -> DICOMNServiceResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await nCreate(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, sopInstanceUID: sopInstanceUID, attributes: attributes)
    }

    /// Sends N-SET, modifying attribute values on a Normalized SOP Instance.
    /// N-SET-RQ always carries a Modification List, so `modifications` is not optional.
    public func nSet(messageID: UInt16, contextID: UInt8, sopClassUID: String, sopInstanceUID: String, modifications: Data) async throws -> DICOMNServiceResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.nSetRequest(messageID: messageID, requestedSOPClassUID: sopClassUID, requestedSOPInstanceUID: sopInstanceUID)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        try await transport.send(.pData(pdvs(data: modifications, contextID: contextID, maximumPayloadLength: maximumPayload)))
        let decoded = try DICOMDIMSECommand.decodeCommandSet(try await receiveCommand(contextID: contextID))
        guard case .nSetResponse(let responseID, let sopClassUID, let sopInstanceUID, let status, _) = decoded, responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
        let dataset = decoded.hasDataset ? try await receiveDataset(contextID: contextID) : nil
        return DICOMNServiceResult(status: status, affectedSOPClassUID: sopClassUID, affectedSOPInstanceUID: sopInstanceUID, dataset: dataset)
    }

    /// Sends N-SET using the accepted presentation context for `sopClassUID`.
    public func nSet(messageID: UInt16, sopClassUID: String, sopInstanceUID: String, modifications: Data) async throws -> DICOMNServiceResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await nSet(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, sopInstanceUID: sopInstanceUID, modifications: modifications)
    }

    /// Sends N-GET, retrieving attribute values from a Normalized SOP Instance.
    /// An empty `attributeIdentifiers` requests every attribute.
    public func nGet(messageID: UInt16, contextID: UInt8, sopClassUID: String, sopInstanceUID: String, attributeIdentifiers: [DICOMTag]) async throws -> DICOMNServiceResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.nGetRequest(messageID: messageID, requestedSOPClassUID: sopClassUID, requestedSOPInstanceUID: sopInstanceUID, attributeIdentifiers: attributeIdentifiers)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        let decoded = try DICOMDIMSECommand.decodeCommandSet(try await receiveCommand(contextID: contextID))
        guard case .nGetResponse(let responseID, let sopClassUID, let sopInstanceUID, let status, _) = decoded, responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
        let dataset = decoded.hasDataset ? try await receiveDataset(contextID: contextID) : nil
        return DICOMNServiceResult(status: status, affectedSOPClassUID: sopClassUID, affectedSOPInstanceUID: sopInstanceUID, dataset: dataset)
    }

    /// Sends N-GET using the accepted presentation context for `sopClassUID`.
    public func nGet(messageID: UInt16, sopClassUID: String, sopInstanceUID: String, attributeIdentifiers: [DICOMTag]) async throws -> DICOMNServiceResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await nGet(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, sopInstanceUID: sopInstanceUID, attributeIdentifiers: attributeIdentifiers)
    }

    /// Sends N-ACTION, invoking a specific action on a Normalized SOP Instance.
    public func nAction(messageID: UInt16, contextID: UInt8, sopClassUID: String, sopInstanceUID: String, actionTypeID: UInt16, actionInformation: Data?) async throws -> DICOMNServiceResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.nActionRequest(messageID: messageID, requestedSOPClassUID: sopClassUID, requestedSOPInstanceUID: sopInstanceUID, actionTypeID: actionTypeID, datasetFollows: actionInformation != nil)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let actionInformation { try await transport.send(.pData(pdvs(data: actionInformation, contextID: contextID, maximumPayloadLength: maximumPayload))) }
        let decoded = try DICOMDIMSECommand.decodeCommandSet(try await receiveCommand(contextID: contextID))
        guard case .nActionResponse(let responseID, let sopClassUID, let sopInstanceUID, _, let status, _) = decoded, responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
        let dataset = decoded.hasDataset ? try await receiveDataset(contextID: contextID) : nil
        return DICOMNServiceResult(status: status, affectedSOPClassUID: sopClassUID, affectedSOPInstanceUID: sopInstanceUID, dataset: dataset)
    }

    /// Sends N-ACTION using the accepted presentation context for `sopClassUID`.
    public func nAction(messageID: UInt16, sopClassUID: String, sopInstanceUID: String, actionTypeID: UInt16, actionInformation: Data?) async throws -> DICOMNServiceResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await nAction(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, sopInstanceUID: sopInstanceUID, actionTypeID: actionTypeID, actionInformation: actionInformation)
    }

    /// Requests Storage Commitment for the instances named in `request`, sending
    /// N-ACTION with Action Type ID 1 against the well-known Storage Commitment
    /// Push Model SOP Instance (`DICOMSOPClass.storageCommitmentPushModelInstance`,
    /// in `DICOMKit`),
    /// encoding the Action Information in `contextID`'s negotiated transfer syntax.
    ///
    /// The part that trips people up: the *result* of the commitment does
    /// **not** come back in the N-ACTION response this method returns — that
    /// response only confirms the SCP accepted the request. The SCP decides
    /// success or failure asynchronously (it may need to actually fetch the
    /// instances from storage) and reports it later as an N-EVENT-REPORT —
    /// Event Type ID 1 when every instance was committed, 2 when some failed —
    /// whose Event Information ``DICOMStorageCommitmentResult`` parses. That
    /// N-EVENT-REPORT can arrive two ways, both already supported elsewhere in
    /// DICOMKit and neither handled by this method:
    /// - On this same association, if the SCU negotiated an SCP role for the
    ///   Storage Commitment Push Model SOP Class via SCP/SCU role selection
    ///   (``DICOMRoleSelection``, checked with ``negotiatedRoles(for:)``), so
    ///   this actor's own ``receiveRequest()`` and ``respondToNEventReport(messageIDBeingRespondedTo:contextID:affectedSOPClassUID:affectedSOPInstanceUID:eventTypeID:status:attributes:)``
    ///   can receive and answer it.
    /// - On a fresh inbound association the SCU accepts separately, typically
    ///   through ``NetworkDICOMULListener``, since many SCPs prefer a new
    ///   connection over negotiating a role reversal.
    public func requestStorageCommitment(messageID: UInt16, contextID: UInt8, _ request: DICOMStorageCommitmentRequest) async throws -> DICOMDIMSEStatus {
        guard let acceptance, let context = acceptance.presentationContexts.first(where: { $0.id == contextID && $0.result == .acceptance }) else {
            throw DICOMAssociationError.notAssociated
        }
        let actionInformation = try request.actionInformation(transferSyntax: TransferSyntax(uid: context.transferSyntaxUID))
        let result = try await nAction(
            messageID: messageID,
            contextID: contextID,
            sopClassUID: DICOMSOPClass.storageCommitmentPushModel,
            sopInstanceUID: DICOMSOPClass.storageCommitmentPushModelInstance,
            actionTypeID: 1,
            actionInformation: actionInformation
        )
        return result.status
    }

    /// Sends N-DELETE, asking the peer to delete a Normalized SOP Instance.
    /// Neither N-DELETE-RQ nor N-DELETE-RSP ever carries a data set.
    public func nDelete(messageID: UInt16, contextID: UInt8, sopClassUID: String, sopInstanceUID: String) async throws -> DICOMNServiceResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.nDeleteRequest(messageID: messageID, requestedSOPClassUID: sopClassUID, requestedSOPInstanceUID: sopInstanceUID)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        guard case .nDeleteResponse(let responseID, let sopClassUID, let sopInstanceUID, let status) = try DICOMDIMSECommand.decodeCommandSet(try await receiveCommand(contextID: contextID)), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
        return DICOMNServiceResult(status: status, affectedSOPClassUID: sopClassUID, affectedSOPInstanceUID: sopInstanceUID, dataset: nil)
    }

    /// Sends N-DELETE using the accepted presentation context for `sopClassUID`.
    public func nDelete(messageID: UInt16, sopClassUID: String, sopInstanceUID: String) async throws -> DICOMNServiceResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await nDelete(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, sopInstanceUID: sopInstanceUID)
    }

    /// Sends N-EVENT-REPORT, notifying the peer of an event on a Normalized SOP Instance.
    public func nEventReport(messageID: UInt16, contextID: UInt8, sopClassUID: String, sopInstanceUID: String, eventTypeID: UInt16, eventInformation: Data?) async throws -> DICOMNServiceResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.nEventReportRequest(messageID: messageID, affectedSOPClassUID: sopClassUID, affectedSOPInstanceUID: sopInstanceUID, eventTypeID: eventTypeID, datasetFollows: eventInformation != nil)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let eventInformation { try await transport.send(.pData(pdvs(data: eventInformation, contextID: contextID, maximumPayloadLength: maximumPayload))) }
        let decoded = try DICOMDIMSECommand.decodeCommandSet(try await receiveCommand(contextID: contextID))
        guard case .nEventReportResponse(let responseID, let sopClassUID, let sopInstanceUID, _, let status, _) = decoded, responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
        let dataset = decoded.hasDataset ? try await receiveDataset(contextID: contextID) : nil
        return DICOMNServiceResult(status: status, affectedSOPClassUID: sopClassUID, affectedSOPInstanceUID: sopInstanceUID, dataset: dataset)
    }

    /// Sends N-EVENT-REPORT using the accepted presentation context for `sopClassUID`.
    public func nEventReport(messageID: UInt16, sopClassUID: String, sopInstanceUID: String, eventTypeID: UInt16, eventInformation: Data?) async throws -> DICOMNServiceResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await nEventReport(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, sopInstanceUID: sopInstanceUID, eventTypeID: eventTypeID, eventInformation: eventInformation)
    }

    /// Receives the next DIMSE request: reassembles the command set from command PDVs
    /// on a single presentation context, then — when the decoded command's
    /// ``DICOMDIMSECommand/hasDataset`` is `true` — reassembles the data set that
    /// follows from PDVs on that same context. Requires an established association;
    /// an SCP obtains one through association acceptance.
    public func receiveRequest() async throws -> DICOMDIMSERequest {
        guard acceptance != nil else { throw DICOMAssociationError.notAssociated }
        var command = Data()
        var contextID: UInt8?
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.isCommand {
                contextID = contextID ?? value.contextID
                guard contextID == value.contextID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                command.append(value.data)
                guard value.isLastFragment else { continue }
                let decoded = try DICOMDIMSECommand.decodeCommandSet(command)
                guard let contextID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                guard decoded.hasDataset else { return DICOMDIMSERequest(command: decoded, contextID: contextID, dataset: nil) }
                var dataset = Data()
                while true {
                    guard case .pData(let datasetValues) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
                    for fragment in datasetValues where fragment.contextID == contextID && !fragment.isCommand {
                        dataset.append(fragment.data)
                        if fragment.isLastFragment { return DICOMDIMSERequest(command: decoded, contextID: contextID, dataset: dataset) }
                    }
                }
            }
        }
    }

    /// Receives the next C-STORE request and its complete dataset. This is the
    /// SCP-side primitive for a C-STORE server.
    ///
    /// It is not usable by a C-GET client: a C-GET SCP interleaves pending C-GET
    /// responses with its C-STORE sub-operations, and those decode as non-C-STORE
    /// commands, so this method would throw partway through the retrieval. Use
    /// ``cGet(messageID:contextID:sopClassUID:identifier:onStore:)`` instead.
    public func receiveCStore() async throws -> DICOMCStoreRequest {
        let request = try await receiveRequest()
        guard case .cStoreRequest(let messageID, let sopClassUID, let sopInstanceUID) = request.command, let dataset = request.dataset else { throw DICOMAssociationError.unexpectedDIMSECommand }
        return DICOMCStoreRequest(messageID: messageID, contextID: request.contextID, sopClassUID: sopClassUID, sopInstanceUID: sopInstanceUID, dataset: dataset)
    }

    /// Sends C-CANCEL-RQ for an outstanding C-FIND, C-MOVE, or C-GET operation.
    public func cCancel(messageIDBeingRespondedTo: UInt16, contextID: UInt8) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.cCancelRequest(messageIDBeingRespondedTo: messageIDBeingRespondedTo)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
    }

    /// Sends C-STORE-RSP for a request received through ``receiveCStore()``.
    public func respond(to request: DICOMCStoreRequest, status: DICOMDIMSEStatus) async throws {
        guard let acceptance else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.cStoreResponse(messageIDBeingRespondedTo: request.messageID, status: status)
        try await transport.send(.pData(try response.commandPDVs(contextID: request.contextID, maximumPayloadLength: maximumPayload)))
    }

    /// Sends C-ECHO-RSP for a request received through ``receiveRequest()``.
    public func respondToCEcho(messageIDBeingRespondedTo: UInt16, contextID: UInt8, status: DICOMDIMSEStatus) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.cEchoResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, status: status)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
    }

    /// Sends C-FIND-RSP for a request received through ``receiveRequest()``. Pass a
    /// non-`nil` `identifier` for a pending response; `nil` for the final response.
    public func respondToCFind(messageIDBeingRespondedTo: UInt16, contextID: UInt8, status: DICOMDIMSEStatus, identifier: Data?, errorComment: String? = nil) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.cFindResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, status: status, identifierFollows: identifier != nil, errorComment: errorComment)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let identifier { try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload))) }
    }

    /// Sends C-MOVE-RSP for a request received through ``receiveRequest()``. Pass a
    /// non-`nil` `identifier` to include a failed-SOP-instance-UID-list dataset.
    public func respondToCMove(messageIDBeingRespondedTo: UInt16, contextID: UInt8, status: DICOMDIMSEStatus, subOperations: DICOMSubOperationCounts?, identifier: Data? = nil, errorComment: String? = nil) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.cMoveResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, status: status, identifierFollows: identifier != nil, subOperations: subOperations, errorComment: errorComment)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let identifier { try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload))) }
    }

    /// Sends C-GET-RSP for a request received through ``receiveRequest()``. Pass a
    /// non-`nil` `identifier` to include a failed-SOP-instance-UID-list dataset.
    public func respondToCGet(messageIDBeingRespondedTo: UInt16, contextID: UInt8, status: DICOMDIMSEStatus, subOperations: DICOMSubOperationCounts?, identifier: Data? = nil, errorComment: String? = nil) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.cGetResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, status: status, identifierFollows: identifier != nil, subOperations: subOperations, errorComment: errorComment)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let identifier { try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload))) }
    }

    // MARK: - N-service SCP responses

    /// Sends N-CREATE-RSP for a request received through ``receiveRequest()``. A
    /// non-`nil` `attributes` becomes the response's Attribute List data set.
    public func respondToNCreate(messageIDBeingRespondedTo: UInt16, contextID: UInt8, affectedSOPClassUID: String?, affectedSOPInstanceUID: String?, status: DICOMDIMSEStatus, attributes: Data? = nil) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.nCreateResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, affectedSOPClassUID: affectedSOPClassUID, affectedSOPInstanceUID: affectedSOPInstanceUID, status: status, datasetFollows: attributes != nil)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let attributes { try await transport.send(.pData(pdvs(data: attributes, contextID: contextID, maximumPayloadLength: maximumPayload))) }
    }

    /// Sends N-SET-RSP for a request received through ``receiveRequest()``. A
    /// non-`nil` `attributes` becomes the response's Attribute List data set.
    public func respondToNSet(messageIDBeingRespondedTo: UInt16, contextID: UInt8, affectedSOPClassUID: String?, affectedSOPInstanceUID: String?, status: DICOMDIMSEStatus, attributes: Data? = nil) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.nSetResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, affectedSOPClassUID: affectedSOPClassUID, affectedSOPInstanceUID: affectedSOPInstanceUID, status: status, datasetFollows: attributes != nil)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let attributes { try await transport.send(.pData(pdvs(data: attributes, contextID: contextID, maximumPayloadLength: maximumPayload))) }
    }

    /// Sends N-GET-RSP for a request received through ``receiveRequest()``. A
    /// non-`nil` `attributes` becomes the response's Attribute List data set.
    public func respondToNGet(messageIDBeingRespondedTo: UInt16, contextID: UInt8, affectedSOPClassUID: String?, affectedSOPInstanceUID: String?, status: DICOMDIMSEStatus, attributes: Data? = nil) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.nGetResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, affectedSOPClassUID: affectedSOPClassUID, affectedSOPInstanceUID: affectedSOPInstanceUID, status: status, datasetFollows: attributes != nil)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let attributes { try await transport.send(.pData(pdvs(data: attributes, contextID: contextID, maximumPayloadLength: maximumPayload))) }
    }

    /// Sends N-ACTION-RSP for a request received through ``receiveRequest()``. A
    /// non-`nil` `attributes` becomes the response's Action Reply data set.
    public func respondToNAction(messageIDBeingRespondedTo: UInt16, contextID: UInt8, affectedSOPClassUID: String?, affectedSOPInstanceUID: String?, actionTypeID: UInt16?, status: DICOMDIMSEStatus, attributes: Data? = nil) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.nActionResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, affectedSOPClassUID: affectedSOPClassUID, affectedSOPInstanceUID: affectedSOPInstanceUID, actionTypeID: actionTypeID, status: status, datasetFollows: attributes != nil)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let attributes { try await transport.send(.pData(pdvs(data: attributes, contextID: contextID, maximumPayloadLength: maximumPayload))) }
    }

    /// Sends N-DELETE-RSP for a request received through ``receiveRequest()``.
    /// N-DELETE-RSP never carries a data set.
    public func respondToNDelete(messageIDBeingRespondedTo: UInt16, contextID: UInt8, affectedSOPClassUID: String?, affectedSOPInstanceUID: String?, status: DICOMDIMSEStatus) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.nDeleteResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, affectedSOPClassUID: affectedSOPClassUID, affectedSOPInstanceUID: affectedSOPInstanceUID, status: status)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
    }

    /// Sends N-EVENT-REPORT-RSP for a request received through ``receiveRequest()``. A
    /// non-`nil` `attributes` becomes the response's Event Reply data set.
    public func respondToNEventReport(messageIDBeingRespondedTo: UInt16, contextID: UInt8, affectedSOPClassUID: String?, affectedSOPInstanceUID: String?, eventTypeID: UInt16?, status: DICOMDIMSEStatus, attributes: Data? = nil) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.nEventReportResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, affectedSOPClassUID: affectedSOPClassUID, affectedSOPInstanceUID: affectedSOPInstanceUID, eventTypeID: eventTypeID, status: status, datasetFollows: attributes != nil)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let attributes { try await transport.send(.pData(pdvs(data: attributes, contextID: contextID, maximumPayloadLength: maximumPayload))) }
    }

    /// Releases an established association. This method is idempotent, including
    /// after an abort or a peer-initiated release.
    public func release() async throws {
        guard acceptance != nil else { return }
        try await transport.send(.releaseRequest)
        guard case .releaseResponse = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
        tearDown()
        await transport.close()
    }

    /// Sends A-ABORT and tears down the association locally. Per PS3.8 Table
    /// 9-26, `source` 0 identifies the DICOM UL service-user and 2 the service
    /// provider; `reason` is only meaningful for a service-provider abort. An
    /// aborted association cannot be released — a subsequent ``release()``
    /// call is a no-op.
    public func abort(source: UInt8 = 0, reason: UInt8 = 0) async throws {
        try await transport.send(.abort(source: source, reason: reason))
        tearDown()
        await transport.close()
    }

    private func tearDown() {
        acceptance = nil
        requestedPresentationContexts = []
    }

    /// Reassembles a DIMSE command set from command PDVs on `contextID`. Shared by the
    /// N-service SCU methods above, whose response handling is otherwise identical.
    private func receiveCommand(contextID: UInt8) async throws -> Data {
        var command = Data()
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID && value.isCommand {
                command.append(value.data)
                if value.isLastFragment { return command }
            }
        }
    }

    /// Reassembles a data set from data PDVs on `contextID`.
    private func receiveDataset(contextID: UInt8) async throws -> Data {
        var dataset = Data()
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID && !value.isCommand {
                dataset.append(value.data)
                if value.isLastFragment { return dataset }
            }
        }
    }

    private func pdvs(data: Data, contextID: UInt8, maximumPayloadLength: Int) -> [DICOMPDataValue] {
        if data.isEmpty { return [DICOMPDataValue(contextID: contextID, isCommand: false, isLastFragment: true, data: Data())] }
        let chunks = stride(from: 0, to: data.count, by: maximumPayloadLength).map { data.subdata(in: $0..<min($0 + maximumPayloadLength, data.count)) }
        return chunks.enumerated().map { DICOMPDataValue(contextID: contextID, isCommand: false, isLastFragment: $0.offset == chunks.count - 1, data: $0.element) }
    }

    /// Receives the next PDU, transparently handling a peer A-ABORT or
    /// A-RELEASE-RQ by tearing down the association and throwing.
    private func receivePDU() async throws -> DICOMULPDU {
        let pdu = try await receiveRawPDU()
        switch pdu {
        case .abort(let source, let reason):
            tearDown()
            await transport.close()
            throw DICOMAssociationError.aborted(source: source, reason: reason)
        case .releaseRequest:
            try await transport.send(.releaseResponse)
            tearDown()
            await transport.close()
            throw DICOMAssociationError.releasedByPeer
        default:
            return pdu
        }
    }

    private func receiveRawPDU() async throws -> DICOMULPDU {
        guard let responseTimeout else { return try await transport.receive() }
        let transport = self.transport
        do {
            return try await withThrowingTaskGroup(of: DICOMULPDU.self) { group in
                group.addTask { try await transport.receive() }
                group.addTask {
                    try await Task.sleep(for: responseTimeout)
                    throw DICOMAssociationError.timedOut
                }
                do {
                    guard let first = try await group.next() else { throw DICOMAssociationError.timedOut }
                    group.cancelAll()
                    return first
                } catch {
                    // `group.cancelAll()` alone cannot free the losing `receive()`: Network
                    // primitives like `NWConnection.receive` ignore Task cancellation, and
                    // `withThrowingTaskGroup` awaits every child before this closure may
                    // return. Close the transport here, before rethrowing, so that await
                    // happens after — not before — the transport unblocks its receiver.
                    group.cancelAll()
                    await transport.close()
                    throw error
                }
            }
        } catch {
            // A timed-out (or otherwise failed) association is dead.
            tearDown()
            throw error
        }
    }
}
