import Foundation

/// An asynchronous byte-transport for complete DICOM Upper Layer PDUs.
///
/// Implement this protocol with Network.framework, a TLS stream, or a test
/// double. The association actor owns protocol ordering; transports only move
/// complete PDUs.
public protocol DICOMULTransport: Sendable {
    func send(_ pdu: DICOMULPDU) async throws
    func receive() async throws -> DICOMULPDU
    func close() async
}

/// Errors generated by the DICOM association state machine.
public enum DICOMAssociationError: Error, Sendable, Equatable {
    case notAssociated
    case rejected(DICOMAssociationRejection)
    case unexpectedPDU
    case unexpectedDIMSECommand
}

/// The final status and identifier datasets returned by a C-FIND operation.
public struct DICOMCFindResult: Sendable, Equatable {
    public let status: UInt16
    public let identifiers: [Data]
    public init(status: UInt16, identifiers: [Data]) { self.status = status; self.identifiers = identifiers }
}

/// A serial DICOM SCU association built on a caller-supplied PDU transport.
public actor DICOMAssociation {
    private let transport: any DICOMULTransport
    private var acceptance: DICOMAssociationAcceptance?

    public init(transport: any DICOMULTransport) { self.transport = transport }

    /// Sends A-ASSOCIATE-RQ and waits for acceptance or rejection.
    @discardableResult
    public func request(_ request: DICOMAssociationRequest) async throws -> DICOMAssociationAcceptance {
        guard acceptance == nil else { throw DICOMAssociationError.unexpectedPDU }
        try await transport.send(.associationRequest(request))
        switch try await transport.receive() {
        case .associationAcceptance(let result): acceptance = result; return result
        case .associationRejection(let rejection): throw DICOMAssociationError.rejected(rejection)
        default: throw DICOMAssociationError.unexpectedPDU
        }
    }

    /// Performs a C-ECHO request and returns the DIMSE status code.
    public func cEcho(messageID: UInt16, contextID: UInt8) async throws -> UInt16 {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let values = try DICOMDIMSECommand.cEchoRequest(messageID: messageID).commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)
        try await transport.send(.pData(values))
        var command = Data()
        while true {
            guard case .pData(let received) = try await transport.receive() else { throw DICOMAssociationError.unexpectedPDU }
            for value in received where value.contextID == contextID && value.isCommand {
                command.append(value.data)
                if value.isLastFragment {
                    guard case .cEchoResponse(let responseID, let status) = try DICOMDIMSECommand.decodeCommandSet(command), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    return status
                }
            }
        }
    }

    /// Sends a C-STORE request and its dataset using the negotiated presentation context.
    /// The dataset must already use that context's negotiated transfer syntax and excludes
    /// the Part 10 File Meta Information.
    public func cStore(messageID: UInt16, contextID: UInt8, sopClassUID: String, sopInstanceUID: String, dataset: Data) async throws -> UInt16 {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.cStoreRequest(messageID: messageID, affectedSOPClassUID: sopClassUID, affectedSOPInstanceUID: sopInstanceUID)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        let dataValues = pdvs(data: dataset, contextID: contextID, maximumPayloadLength: maximumPayload)
        try await transport.send(.pData(dataValues))
        var response = Data()
        while true {
            guard case .pData(let values) = try await transport.receive() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID && value.isCommand {
                response.append(value.data)
                if value.isLastFragment {
                    guard case .cStoreResponse(let responseID, let status) = try DICOMDIMSECommand.decodeCommandSet(response), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    return status
                }
            }
        }
    }

    /// Performs C-FIND, collecting identifier datasets for every pending response.
    public func cFind(messageID: UInt16, contextID: UInt8, sopClassUID: String, identifier: Data) async throws -> DICOMCFindResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        try await transport.send(.pData(try DICOMDIMSECommand.cFindRequest(messageID: messageID, affectedSOPClassUID: sopClassUID).commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload)))
        var identifiers: [Data] = []
        var responseCommand = Data()
        while true {
            guard case .pData(let values) = try await transport.receive() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID {
                if value.isCommand {
                    responseCommand.append(value.data)
                    guard value.isLastFragment else { continue }
                    guard case .cFindResponse(let responseID, let status) = try DICOMDIMSECommand.decodeCommandSet(responseCommand), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    responseCommand.removeAll(keepingCapacity: true)
                    if !isPending(status) { return DICOMCFindResult(status: status, identifiers: identifiers) }
                } else {
                    // Each pending response includes one identifier dataset. A production
                    // SCP sends the command PDU before this dataset PDU.
                    identifiers.append(value.data)
                }
            }
        }
    }

    /// Performs C-MOVE and returns its final DIMSE status. Pending progress
    /// responses are consumed until the peer emits a final response.
    public func cMove(messageID: UInt16, contextID: UInt8, sopClassUID: String, destination: String, identifier: Data) async throws -> UInt16 {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.cMoveRequest(messageID: messageID, affectedSOPClassUID: sopClassUID, moveDestination: destination)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload)))
        var response = Data()
        while true {
            guard case .pData(let values) = try await transport.receive() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID && value.isCommand {
                response.append(value.data)
                guard value.isLastFragment else { continue }
                guard case .cMoveResponse(let responseID, let status) = try DICOMDIMSECommand.decodeCommandSet(response), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                response.removeAll(keepingCapacity: true)
                if !isPending(status) { return status }
            }
        }
    }

    /// Performs C-GET and returns the final DIMSE status. The caller must
    /// separately negotiate storage presentation contexts to accept C-STORE
    /// sub-operations sent by the peer during a pending C-GET response.
    public func cGet(messageID: UInt16, contextID: UInt8, sopClassUID: String, identifier: Data) async throws -> UInt16 {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        try await transport.send(.pData(try DICOMDIMSECommand.cGetRequest(messageID: messageID, affectedSOPClassUID: sopClassUID).commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload)))
        var response = Data()
        while true {
            guard case .pData(let values) = try await transport.receive() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID && value.isCommand {
                response.append(value.data)
                guard value.isLastFragment else { continue }
                guard case .cGetResponse(let responseID, let status) = try DICOMDIMSECommand.decodeCommandSet(response), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                response.removeAll(keepingCapacity: true)
                if !isPending(status) { return status }
            }
        }
    }

    /// Releases an established association. This method is idempotent.
    public func release() async throws {
        guard acceptance != nil else { return }
        try await transport.send(.releaseRequest)
        guard case .releaseResponse = try await transport.receive() else { throw DICOMAssociationError.unexpectedPDU }
        acceptance = nil
        await transport.close()
    }

    private func pdvs(data: Data, contextID: UInt8, maximumPayloadLength: Int) -> [DICOMPDataValue] {
        if data.isEmpty { return [DICOMPDataValue(contextID: contextID, isCommand: false, isLastFragment: true, data: Data())] }
        let chunks = stride(from: 0, to: data.count, by: maximumPayloadLength).map { data.subdata(in: $0..<min($0 + maximumPayloadLength, data.count)) }
        return chunks.enumerated().map { DICOMPDataValue(contextID: contextID, isCommand: false, isLastFragment: $0.offset == chunks.count - 1, data: $0.element) }
    }

    private func isPending(_ status: UInt16) -> Bool { status == 0xFF00 || status == 0xFF01 }
}
