import Foundation

/// An asynchronous byte-transport for complete DICOM Upper Layer PDUs.
///
/// Implement this protocol with Network.framework, a TLS stream, or a test
/// double. The association actor owns protocol ordering; transports only move
/// complete PDUs.
public protocol DICOMULTransport: Sendable {
    func send(_ pdu: DICOMULPDU) async throws
    func receive() async throws -> DICOMULPDU
    func close() async
}

/// Errors generated by the DICOM association state machine.
public enum DICOMAssociationError: Error, Sendable, Equatable {
    case notAssociated
    case rejected(DICOMAssociationRejection)
    case unexpectedPDU
    case unexpectedDIMSECommand
    case timedOut
    case aborted(source: UInt8, reason: UInt8)
    case releasedByPeer
}

/// The final status and identifier datasets returned by a C-FIND operation.
public struct DICOMCFindResult: Sendable, Equatable {
    public let status: DICOMDIMSEStatus
    public let identifiers: [Data]
    public init(status: DICOMDIMSEStatus, identifiers: [Data]) { self.status = status; self.identifiers = identifiers }
}

/// The final status, sub-operation progress, and error comment returned by a C-MOVE operation.
public struct DICOMCMoveResult: Sendable, Equatable {
    public let status: DICOMDIMSEStatus
    public let subOperations: DICOMSubOperationCounts?
    public let errorComment: String?
    public init(status: DICOMDIMSEStatus, subOperations: DICOMSubOperationCounts?, errorComment: String?) {
        self.status = status; self.subOperations = subOperations; self.errorComment = errorComment
    }
}

/// The final status, sub-operation progress, and error comment returned by a C-GET operation.
public struct DICOMCGetResult: Sendable, Equatable {
    public let status: DICOMDIMSEStatus
    public let subOperations: DICOMSubOperationCounts?
    public let errorComment: String?
    public init(status: DICOMDIMSEStatus, subOperations: DICOMSubOperationCounts?, errorComment: String?) {
        self.status = status; self.subOperations = subOperations; self.errorComment = errorComment
    }
}

/// A DIMSE request received by an SCP through ``DICOMAssociation/receiveRequest()``.
public struct DICOMDIMSERequest: Sendable, Equatable {
    public let command: DICOMDIMSECommand
    public let contextID: UInt8
    public let dataset: Data?
    public init(command: DICOMDIMSECommand, contextID: UInt8, dataset: Data?) {
        self.command = command; self.contextID = contextID; self.dataset = dataset
    }
}

/// An incoming C-STORE request awaiting an SCP response.
public struct DICOMCStoreRequest: Sendable, Equatable {
    public let messageID: UInt16
    public let contextID: UInt8
    public let sopClassUID: String
    public let sopInstanceUID: String
    public let dataset: Data
    public init(messageID: UInt16, contextID: UInt8, sopClassUID: String, sopInstanceUID: String, dataset: Data) {
        self.messageID = messageID; self.contextID = contextID; self.sopClassUID = sopClassUID; self.sopInstanceUID = sopInstanceUID; self.dataset = dataset
    }
}

/// A serial DICOM SCU association built on a caller-supplied PDU transport.
public actor DICOMAssociation {
    private let transport: any DICOMULTransport
    private let responseTimeout: Duration?
    private var acceptance: DICOMAssociationAcceptance?
    private var requestedPresentationContexts: [DICOMPresentationContext] = []

    /// Creates an association. A non-`nil` timeout applies to every peer PDU
    /// awaited by this actor, including association negotiation and DIMSE responses.
    public init(transport: any DICOMULTransport, responseTimeout: Duration? = nil) {
        self.transport = transport
        self.responseTimeout = responseTimeout
    }

    /// Sends A-ASSOCIATE-RQ and waits for acceptance or rejection.
    @discardableResult
    public func request(_ request: DICOMAssociationRequest) async throws -> DICOMAssociationAcceptance {
        guard acceptance == nil else { throw DICOMAssociationError.unexpectedPDU }
        requestedPresentationContexts = request.presentationContexts
        try await transport.send(.associationRequest(request))
        switch try await receivePDU() {
        case .associationAcceptance(let result): acceptance = result; return result
        case .associationRejection(let rejection): throw DICOMAssociationError.rejected(rejection)
        default: throw DICOMAssociationError.unexpectedPDU
        }
    }

    /// Waits for the peer's A-ASSOCIATE-RQ. Pass the result to ``accept(_:policy:)``
    /// to negotiate and respond. Throws ``DICOMAssociationError/unexpectedPDU`` if
    /// this association is already established or the peer sends any other PDU.
    public func receiveAssociationRequest() async throws -> DICOMAssociationRequest {
        guard acceptance == nil else { throw DICOMAssociationError.unexpectedPDU }
        guard case .associationRequest(let request) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
        return request
    }

    /// Negotiates `request` against `policy` and sends the resulting A-ASSOCIATE-AC
    /// or A-ASSOCIATE-RJ. On acceptance, records the association state so that
    /// ``receiveRequest()``, the `respondTo…` helpers, ``presentationContextID(for:)``,
    /// and ``negotiatedRoles(for:)`` behave as they do for an SCU. On rejection, closes
    /// the transport and throws ``DICOMAssociationError/rejected(_:)`` with the
    /// rejection that was sent.
    @discardableResult
    public func accept(_ request: DICOMAssociationRequest, policy: DICOMAssociationPolicy) async throws -> DICOMAssociationAcceptance {
        switch policy.negotiate(request) {
        case .accept(let result):
            requestedPresentationContexts = request.presentationContexts
            try await transport.send(.associationAcceptance(result))
            acceptance = result
            return result
        case .reject(let rejection):
            try await transport.send(.associationRejection(rejection))
            await transport.close()
            throw DICOMAssociationError.rejected(rejection)
        }
    }

    /// Returns the negotiated presentation-context ID for an abstract syntax
    /// (normally a SOP Class UID), or `nil` when it was not accepted.
    public func presentationContextID(for abstractSyntaxUID: String) -> UInt8? {
        guard let acceptance else { return nil }
        return requestedPresentationContexts.first { requested in
            requested.abstractSyntaxUID == abstractSyntaxUID && acceptance.presentationContexts.contains { accepted in
                accepted.id == requested.id && accepted.result == .acceptance
            }
        }?.id
    }

    /// Performs a C-ECHO request and returns the DIMSE status code.
    public func cEcho(messageID: UInt16, contextID: UInt8) async throws -> DICOMDIMSEStatus {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let values = try DICOMDIMSECommand.cEchoRequest(messageID: messageID).commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)
        try await transport.send(.pData(values))
        var command = Data()
        while true {
            guard case .pData(let received) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in received where value.contextID == contextID && value.isCommand {
                command.append(value.data)
                if value.isLastFragment {
                    guard case .cEchoResponse(let responseID, let status) = try DICOMDIMSECommand.decodeCommandSet(command), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    return status
                }
            }
        }
    }

    /// Sends a C-STORE request and its dataset using the negotiated presentation context.
    /// The dataset must already use that context's negotiated transfer syntax and excludes
    /// the Part 10 File Meta Information.
    public func cStore(messageID: UInt16, contextID: UInt8, sopClassUID: String, sopInstanceUID: String, dataset: Data) async throws -> DICOMDIMSEStatus {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.cStoreRequest(messageID: messageID, affectedSOPClassUID: sopClassUID, affectedSOPInstanceUID: sopInstanceUID)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        let dataValues = pdvs(data: dataset, contextID: contextID, maximumPayloadLength: maximumPayload)
        try await transport.send(.pData(dataValues))
        var response = Data()
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID && value.isCommand {
                response.append(value.data)
                if value.isLastFragment {
                    guard case .cStoreResponse(let responseID, let status) = try DICOMDIMSECommand.decodeCommandSet(response), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    return status
                }
            }
        }
    }

    /// Sends C-STORE using the accepted presentation context for `sopClassUID`.
    public func cStore(messageID: UInt16, sopClassUID: String, sopInstanceUID: String, dataset: Data) async throws -> DICOMDIMSEStatus {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await cStore(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, sopInstanceUID: sopInstanceUID, dataset: dataset)
    }

    /// Performs C-FIND, collecting identifier datasets for every pending response.
    public func cFind(messageID: UInt16, contextID: UInt8, sopClassUID: String, identifier: Data) async throws -> DICOMCFindResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        try await transport.send(.pData(try DICOMDIMSECommand.cFindRequest(messageID: messageID, affectedSOPClassUID: sopClassUID).commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload)))
        var identifiers: [Data] = []
        var responseCommand = Data()
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID {
                if value.isCommand {
                    responseCommand.append(value.data)
                    guard value.isLastFragment else { continue }
                    guard case .cFindResponse(let responseID, let status, _, _) = try DICOMDIMSECommand.decodeCommandSet(responseCommand), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    responseCommand.removeAll(keepingCapacity: true)
                    if !status.isPending { return DICOMCFindResult(status: status, identifiers: identifiers) }
                } else {
                    // Each pending response includes one identifier dataset. A production
                    // SCP sends the command PDU before this dataset PDU.
                    identifiers.append(value.data)
                }
            }
        }
    }

    /// Performs C-FIND using the accepted presentation context for `sopClassUID`.
    public func cFind(messageID: UInt16, sopClassUID: String, identifier: Data) async throws -> DICOMCFindResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await cFind(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, identifier: identifier)
    }

    /// Performs C-MOVE and returns its final DIMSE status. Pending progress
    /// responses are consumed until the peer emits a final response.
    public func cMove(messageID: UInt16, contextID: UInt8, sopClassUID: String, destination: String, identifier: Data) async throws -> DICOMCMoveResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.cMoveRequest(messageID: messageID, affectedSOPClassUID: sopClassUID, moveDestination: destination)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload)))
        var response = Data()
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID && value.isCommand {
                response.append(value.data)
                guard value.isLastFragment else { continue }
                guard case .cMoveResponse(let responseID, let status, _, let subOperations, let errorComment) = try DICOMDIMSECommand.decodeCommandSet(response), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                response.removeAll(keepingCapacity: true)
                if !status.isPending { return DICOMCMoveResult(status: status, subOperations: subOperations, errorComment: errorComment) }
            }
        }
    }

    /// Performs C-MOVE using the accepted presentation context for `sopClassUID`.
    public func cMove(messageID: UInt16, sopClassUID: String, destination: String, identifier: Data) async throws -> DICOMCMoveResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await cMove(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, destination: destination, identifier: identifier)
    }

    /// Returns the accepted SCP/SCU role selection for `sopClassUID` from the
    /// A-ASSOCIATE-AC, or `nil` when the peer did not negotiate one.
    public func negotiatedRoles(for sopClassUID: String) -> DICOMRoleSelection? {
        acceptance?.roleSelections.first { $0.sopClassUID == sopClassUID }
    }

    /// Performs C-GET and returns the final DIMSE status. The caller must
    /// separately negotiate storage presentation contexts to accept C-STORE
    /// sub-operations sent by the peer during a pending C-GET response. Per
    /// PS3.7 Annex D.3.3.4, a C-GET SCU must propose an SCP role in SCP/SCU
    /// role selection negotiation for each storage SOP Class it expects to
    /// receive during the exchange.
    public func cGet(messageID: UInt16, contextID: UInt8, sopClassUID: String, identifier: Data) async throws -> DICOMCGetResult {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        try await transport.send(.pData(try DICOMDIMSECommand.cGetRequest(messageID: messageID, affectedSOPClassUID: sopClassUID).commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload)))
        var response = Data()
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.contextID == contextID && value.isCommand {
                response.append(value.data)
                guard value.isLastFragment else { continue }
                guard case .cGetResponse(let responseID, let status, _, let subOperations, let errorComment) = try DICOMDIMSECommand.decodeCommandSet(response), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                response.removeAll(keepingCapacity: true)
                if !status.isPending { return DICOMCGetResult(status: status, subOperations: subOperations, errorComment: errorComment) }
            }
        }
    }

    /// Performs C-GET using the accepted presentation context for `sopClassUID`.
    public func cGet(messageID: UInt16, sopClassUID: String, identifier: Data) async throws -> DICOMCGetResult {
        guard let contextID = presentationContextID(for: sopClassUID) else { throw DICOMAssociationError.notAssociated }
        return try await cGet(messageID: messageID, contextID: contextID, sopClassUID: sopClassUID, identifier: identifier)
    }

    /// Receives the next DIMSE request: reassembles the command set from command PDVs
    /// on a single presentation context, then — when the decoded command's
    /// ``DICOMDIMSECommand/hasDataset`` is `true` — reassembles the data set that
    /// follows from PDVs on that same context. Requires an established association;
    /// an SCP obtains one through association acceptance.
    public func receiveRequest() async throws -> DICOMDIMSERequest {
        guard acceptance != nil else { throw DICOMAssociationError.notAssociated }
        var command = Data()
        var contextID: UInt8?
        while true {
            guard case .pData(let values) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
            for value in values where value.isCommand {
                contextID = contextID ?? value.contextID
                guard contextID == value.contextID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                command.append(value.data)
                guard value.isLastFragment else { continue }
                let decoded = try DICOMDIMSECommand.decodeCommandSet(command)
                guard let contextID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                guard decoded.hasDataset else { return DICOMDIMSERequest(command: decoded, contextID: contextID, dataset: nil) }
                var dataset = Data()
                while true {
                    guard case .pData(let datasetValues) = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
                    for fragment in datasetValues where fragment.contextID == contextID && !fragment.isCommand {
                        dataset.append(fragment.data)
                        if fragment.isLastFragment { return DICOMDIMSERequest(command: decoded, contextID: contextID, dataset: dataset) }
                    }
                }
            }
        }
    }

    /// Receives the next C-STORE request and its complete dataset. This is the
    /// SCP-side primitive used directly by C-STORE servers and C-GET clients.
    public func receiveCStore() async throws -> DICOMCStoreRequest {
        let request = try await receiveRequest()
        guard case .cStoreRequest(let messageID, let sopClassUID, let sopInstanceUID) = request.command, let dataset = request.dataset else { throw DICOMAssociationError.unexpectedDIMSECommand }
        return DICOMCStoreRequest(messageID: messageID, contextID: request.contextID, sopClassUID: sopClassUID, sopInstanceUID: sopInstanceUID, dataset: dataset)
    }

    /// Sends C-CANCEL-RQ for an outstanding C-FIND, C-MOVE, or C-GET operation.
    public func cCancel(messageIDBeingRespondedTo: UInt16, contextID: UInt8) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let command = DICOMDIMSECommand.cCancelRequest(messageIDBeingRespondedTo: messageIDBeingRespondedTo)
        try await transport.send(.pData(try command.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
    }

    /// Sends C-STORE-RSP for a request received through ``receiveCStore()``.
    public func respond(to request: DICOMCStoreRequest, status: DICOMDIMSEStatus) async throws {
        guard let acceptance else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.cStoreResponse(messageIDBeingRespondedTo: request.messageID, status: status)
        try await transport.send(.pData(try response.commandPDVs(contextID: request.contextID, maximumPayloadLength: maximumPayload)))
    }

    /// Sends C-ECHO-RSP for a request received through ``receiveRequest()``.
    public func respondToCEcho(messageIDBeingRespondedTo: UInt16, contextID: UInt8, status: DICOMDIMSEStatus) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.cEchoResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, status: status)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
    }

    /// Sends C-FIND-RSP for a request received through ``receiveRequest()``. Pass a
    /// non-`nil` `identifier` for a pending response; `nil` for the final response.
    public func respondToCFind(messageIDBeingRespondedTo: UInt16, contextID: UInt8, status: DICOMDIMSEStatus, identifier: Data?, errorComment: String? = nil) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.cFindResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, status: status, identifierFollows: identifier != nil, errorComment: errorComment)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let identifier { try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload))) }
    }

    /// Sends C-MOVE-RSP for a request received through ``receiveRequest()``. Pass a
    /// non-`nil` `identifier` to include a failed-SOP-instance-UID-list dataset.
    public func respondToCMove(messageIDBeingRespondedTo: UInt16, contextID: UInt8, status: DICOMDIMSEStatus, subOperations: DICOMSubOperationCounts?, identifier: Data? = nil, errorComment: String? = nil) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.cMoveResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, status: status, identifierFollows: identifier != nil, subOperations: subOperations, errorComment: errorComment)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let identifier { try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload))) }
    }

    /// Sends C-GET-RSP for a request received through ``receiveRequest()``. Pass a
    /// non-`nil` `identifier` to include a failed-SOP-instance-UID-list dataset.
    public func respondToCGet(messageIDBeingRespondedTo: UInt16, contextID: UInt8, status: DICOMDIMSEStatus, subOperations: DICOMSubOperationCounts?, identifier: Data? = nil, errorComment: String? = nil) async throws {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let response = DICOMDIMSECommand.cGetResponse(messageIDBeingRespondedTo: messageIDBeingRespondedTo, status: status, identifierFollows: identifier != nil, subOperations: subOperations, errorComment: errorComment)
        try await transport.send(.pData(try response.commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)))
        if let identifier { try await transport.send(.pData(pdvs(data: identifier, contextID: contextID, maximumPayloadLength: maximumPayload))) }
    }

    /// Releases an established association. This method is idempotent, including
    /// after an abort or a peer-initiated release.
    public func release() async throws {
        guard acceptance != nil else { return }
        try await transport.send(.releaseRequest)
        guard case .releaseResponse = try await receivePDU() else { throw DICOMAssociationError.unexpectedPDU }
        tearDown()
        await transport.close()
    }

    /// Sends A-ABORT and tears down the association locally. Per PS3.8 Table
    /// 9-26, `source` 0 identifies the DICOM UL service-user and 2 the service
    /// provider; `reason` is only meaningful for a service-provider abort. An
    /// aborted association cannot be released — a subsequent ``release()``
    /// call is a no-op.
    public func abort(source: UInt8 = 0, reason: UInt8 = 0) async throws {
        try await transport.send(.abort(source: source, reason: reason))
        tearDown()
        await transport.close()
    }

    private func tearDown() {
        acceptance = nil
        requestedPresentationContexts = []
    }

    private func pdvs(data: Data, contextID: UInt8, maximumPayloadLength: Int) -> [DICOMPDataValue] {
        if data.isEmpty { return [DICOMPDataValue(contextID: contextID, isCommand: false, isLastFragment: true, data: Data())] }
        let chunks = stride(from: 0, to: data.count, by: maximumPayloadLength).map { data.subdata(in: $0..<min($0 + maximumPayloadLength, data.count)) }
        return chunks.enumerated().map { DICOMPDataValue(contextID: contextID, isCommand: false, isLastFragment: $0.offset == chunks.count - 1, data: $0.element) }
    }

    /// Receives the next PDU, transparently handling a peer A-ABORT or
    /// A-RELEASE-RQ by tearing down the association and throwing.
    private func receivePDU() async throws -> DICOMULPDU {
        let pdu = try await receiveRawPDU()
        switch pdu {
        case .abort(let source, let reason):
            tearDown()
            await transport.close()
            throw DICOMAssociationError.aborted(source: source, reason: reason)
        case .releaseRequest:
            try await transport.send(.releaseResponse)
            tearDown()
            await transport.close()
            throw DICOMAssociationError.releasedByPeer
        default:
            return pdu
        }
    }

    private func receiveRawPDU() async throws -> DICOMULPDU {
        guard let responseTimeout else { return try await transport.receive() }
        let transport = self.transport
        return try await withThrowingTaskGroup(of: DICOMULPDU.self) { group in
            group.addTask { try await transport.receive() }
            group.addTask {
                try await Task.sleep(for: responseTimeout)
                throw DICOMAssociationError.timedOut
            }
            guard let first = try await group.next() else { throw DICOMAssociationError.timedOut }
            group.cancelAll()
            return first
        }
    }
}
