import Foundation

/// An asynchronous byte-transport for complete DICOM Upper Layer PDUs.
///
/// Implement this protocol with Network.framework, a TLS stream, or a test
/// double. The association actor owns protocol ordering; transports only move
/// complete PDUs.
public protocol DICOMULTransport: Sendable {
    func send(_ pdu: DICOMULPDU) async throws
    func receive() async throws -> DICOMULPDU
    func close() async
}

/// Errors generated by the DICOM association state machine.
public enum DICOMAssociationError: Error, Sendable, Equatable {
    case notAssociated
    case rejected(DICOMAssociationRejection)
    case unexpectedPDU
    case unexpectedDIMSECommand
}

/// A serial DICOM SCU association built on a caller-supplied PDU transport.
public actor DICOMAssociation {
    private let transport: any DICOMULTransport
    private var acceptance: DICOMAssociationAcceptance?

    public init(transport: any DICOMULTransport) { self.transport = transport }

    /// Sends A-ASSOCIATE-RQ and waits for acceptance or rejection.
    @discardableResult
    public func request(_ request: DICOMAssociationRequest) async throws -> DICOMAssociationAcceptance {
        guard acceptance == nil else { throw DICOMAssociationError.unexpectedPDU }
        try await transport.send(.associationRequest(request))
        switch try await transport.receive() {
        case .associationAcceptance(let result): acceptance = result; return result
        case .associationRejection(let rejection): throw DICOMAssociationError.rejected(rejection)
        default: throw DICOMAssociationError.unexpectedPDU
        }
    }

    /// Performs a C-ECHO request and returns the DIMSE status code.
    public func cEcho(messageID: UInt16, contextID: UInt8) async throws -> UInt16 {
        guard let acceptance, acceptance.presentationContexts.contains(where: { $0.id == contextID && $0.result == .acceptance }) else { throw DICOMAssociationError.notAssociated }
        let maximumPayload = max(1, Int(acceptance.maximumPDULength) - 12)
        let values = try DICOMDIMSECommand.cEchoRequest(messageID: messageID).commandPDVs(contextID: contextID, maximumPayloadLength: maximumPayload)
        try await transport.send(.pData(values))
        var command = Data()
        while true {
            guard case .pData(let received) = try await transport.receive() else { throw DICOMAssociationError.unexpectedPDU }
            for value in received where value.contextID == contextID && value.isCommand {
                command.append(value.data)
                if value.isLastFragment {
                    guard case .cEchoResponse(let responseID, let status) = try DICOMDIMSECommand.decodeCommandSet(command), responseID == messageID else { throw DICOMAssociationError.unexpectedDIMSECommand }
                    return status
                }
            }
        }
    }

    /// Releases an established association. This method is idempotent.
    public func release() async throws {
        guard acceptance != nil else { return }
        try await transport.send(.releaseRequest)
        guard case .releaseResponse = try await transport.receive() else { throw DICOMAssociationError.unexpectedPDU }
        acceptance = nil
        await transport.close()
    }
}
