import Foundation
import Testing
@testable import DICOMKit

/// Tests for the PS3.15 Table E.1-1 generated confidentiality table.
///
/// `DICOMDeidentificationTable` is internal and generated by
/// `Tools/generate_deidentification_profile.py`; these tests exercise it
/// directly to keep the generator honest before the public
/// `DICOMConfidentialityProfile` model is layered on top of it.
struct DICOMDeidentificationTableTests {
    @Test func generatesExpectedNumberOfEntries() {
        // Table E.1-1 (2025a) has 631 attribute rows: 627 exact tags, 3
        // repeating-group ("xx") tags, and 1 dropped "Private Attributes"
        // placeholder row that isn't a concrete or maskable tag.
        #expect(DICOMDeidentificationTable.entries.count == 627)
        #expect(DICOMDeidentificationTable.maskedEntries.count == 3)
    }

    @Test func patientNameIsReplacedWithZeroLengthUnderBasicProfile() {
        let entry = DICOMDeidentificationTable.entries[.patientName]

        #expect(entry?.basic == "Z")
        #expect(entry?.overrides.isEmpty == true)
    }

    @Test func accessionNumberIsReplacedWithZeroLengthUnderBasicProfile() {
        let entry = DICOMDeidentificationTable.entries[DICOMTag(group: 0x0008, element: 0x0050)]

        #expect(entry?.basic == "Z")
    }

    @Test func acquisitionCommentsIsRemovedWithCleanDescriptorOverride() {
        let entry = DICOMDeidentificationTable.entries[DICOMTag(group: 0x0018, element: 0x4000)]

        #expect(entry?.basic == "X")
        // Column index 7 = Clean Desc. Opt.
        #expect(entry?.overrides[7] == "C")
    }

    @Test func studyInstanceUIDIsRemappedWithRetainUIDsOverride() {
        let entry = DICOMDeidentificationTable.entries[.studyInstanceUID]

        #expect(entry?.basic == "U")
        // Column index 1 = Rtn. UIDs Opt.
        #expect(entry?.overrides[1] == "K")
    }

    @Test func repeatingGroupTagsAreMaskedRatherThanDropped() {
        // Curve Data (50xx,xxxx): Basic Profile X.
        let curveData = DICOMTag(group: 0x5012, element: 0x1234)
        let match = DICOMDeidentificationTable.maskedEntries.first { $0.matches(curveData) }

        #expect(match?.basic == "X")
        // Column index 9 = Clean Graph. Opt.
        #expect(match?.overrides[9] == "C")

        // Overlay Comments (60xx,4000) and Overlay Data (60xx,3000) also match by group mask only on their fixed element.
        #expect(DICOMDeidentificationTable.maskedEntries.contains { $0.matches(DICOMTag(group: 0x6010, element: 0x4000)) })
        #expect(DICOMDeidentificationTable.maskedEntries.contains { $0.matches(DICOMTag(group: 0x6010, element: 0x3000)) })
        #expect(DICOMDeidentificationTable.maskedEntries.contains { $0.matches(DICOMTag(group: 0x6010, element: 0x0010)) } == false)
    }
}

/// Tests for the public `DICOMConfidentialityProfile` model built on top of
/// `DICOMDeidentificationTable`.
struct DICOMConfidentialityProfileTests {
    private let accessionNumber = DICOMTag(group: 0x0008, element: 0x0050)
    private let acquisitionComments = DICOMTag(group: 0x0018, element: 0x4000)
    private let patientID = DICOMTag(group: 0x0010, element: 0x0020)
    private let patientSex = DICOMTag(group: 0x0010, element: 0x0040)
    private let patientBirthDate = DICOMTag(group: 0x0010, element: 0x0030)
    private let contentDate = DICOMTag(group: 0x0008, element: 0x0023)
    private let attributeModificationDateTime = DICOMTag(group: 0x0400, element: 0x0562)
    private let rows = DICOMTag(group: 0x0028, element: 0x0010)
    private let columns = DICOMTag(group: 0x0028, element: 0x0011)

    @Test func basicProfileMapsZCodedAttributesToPresentZeroLengthAndXCodedAttributesToRemoval() {
        let profile = DICOMConfidentialityProfile()

        #expect(profile.action(for: .patientName) == .replaceWithZeroLength)
        #expect(profile.action(for: accessionNumber) == .replaceWithZeroLength)
        #expect(profile.action(for: acquisitionComments) == .remove)

        // `Z` (replaceWithZeroLength) keeps the element present with an
        // empty value — Table E.1-1 codes `Z` for attributes that are
        // typically Type 2 in their IOD, so removing them would make the
        // output non-conformant. `X` (remove) actually drops the element.
        let dataset = DICOMDataset(elements: [
            DICOMElement(tag: .patientName, vr: .PN, value: Data("Doe^Jane".utf8)),
            DICOMElement(tag: accessionNumber, vr: .SH, value: Data("ACC-1".utf8)),
            DICOMElement(tag: acquisitionComments, vr: .LT, value: Data("comment".utf8))
        ])
        let result = profile.makeAnonymizer(replacement: "Anonymous").anonymize(dataset)

        #expect(result[.patientName] == DICOMElement(tag: .patientName, vr: .PN, value: Data()))
        #expect(result[accessionNumber] == DICOMElement(tag: accessionNumber, vr: .SH, value: Data()))
        #expect(result[acquisitionComments] == nil)
    }

    @Test func patientNameUnderBareBasicProfileIsPresentAndZeroLength() {
        let profile = DICOMConfidentialityProfile()
        let dataset = DICOMDataset(elements: [DICOMElement(tag: .patientName, vr: .PN, value: Data("Doe^Jane".utf8))])

        let result = profile.makeAnonymizer(replacement: "Anonymous").anonymize(dataset)

        #expect(result[.patientName] != nil)
        #expect(result[.patientName]?.stringValue == "")
        #expect(result[.patientName]?.vr == .PN)
    }

    @Test func sequenceCodedZBecomesAnEmptySequenceRatherThanBeingRemoved() {
        // Verifying Observer Identification Code Sequence (0040,A088) is a
        // real Table E.1-1 row coded bare `Z` whose VR is SQ.
        let tag = DICOMTag(group: 0x0040, element: 0xA088)
        let profile = DICOMConfidentialityProfile()
        let nestedCodeValue = DICOMTag(group: 0x0008, element: 0x0100)
        let nested = DICOMDataset(elements: [DICOMElement(tag: nestedCodeValue, vr: .SH, value: Data("121008".utf8))])
        let dataset = DICOMDataset(elements: [DICOMElement(tag: tag, vr: .SQ, value: Data(), sequenceItems: [nested])])

        #expect(profile.action(for: tag) == .replaceWithZeroLength)

        let result = profile.makeAnonymizer(replacement: "Anonymous").anonymize(dataset)

        #expect(result[tag]?.vr == .SQ)
        #expect(result[tag]?.sequenceItems == [])
    }

    @Test func retainUIDsOptionKeepsStudyInstanceUIDWhereBareProfileRemaps() {
        let bare = DICOMConfidentialityProfile()
        let retainUIDs = DICOMConfidentialityProfile(options: [.retainUIDs])

        #expect(bare.action(for: .studyInstanceUID) == .replaceUID)
        #expect(retainUIDs.action(for: .studyInstanceUID) == .keep)
    }

    @Test func retainPatientCharacteristicsOptionKeepsPatientSex() {
        let bare = DICOMConfidentialityProfile()
        let retainCharacteristics = DICOMConfidentialityProfile(options: [.retainPatientCharacteristics])

        #expect(bare.action(for: patientSex) == .replaceWithZeroLength)
        #expect(retainCharacteristics.action(for: patientSex) == .keep)
    }

    @Test func attributeAbsentFromTableReturnsNilSoCallerKeepsIt() {
        let profile = DICOMConfidentialityProfile()

        #expect(profile.action(for: rows) == nil)
        #expect(profile.action(for: columns) == nil)
    }

    @Test func laterOptionColumnWinsWhenTwoSelectedOptionsOverrideTheSameAttribute() {
        // Content Date has both a Retain Longitudinal Full Dates override
        // (K) and a Retain Longitudinal Modified Dates override (C).
        // Selecting both is documented to resolve to the later column,
        // i.e. Clean (C), not Keep (K).
        let both = DICOMConfidentialityProfile(options: [.retainLongitudinalFullDates, .retainLongitudinalModifiedDates])

        #expect(both.action(for: contentDate) == .clean)
    }

    @Test func makeAnonymizerReplacesDummyCodedAttributesWithTheReplacementText() {
        let profile = DICOMConfidentialityProfile()
        let dataset = DICOMDataset(elements: [
            DICOMElement(tag: attributeModificationDateTime, vr: .DT, value: Data("20240101".utf8))
        ])

        let result = profile.makeAnonymizer(replacement: "REDACTED").anonymize(dataset)

        #expect(result[attributeModificationDateTime]?.stringValue == "REDACTED")
    }

    @Test func basicApplicationLevelConfidentialityLeavesZCodedPatientIdentifiersPresentAndZeroLength() {
        // Table E.1-1 codes Patient's Name, Patient ID, Accession Number, and
        // Patient's Birth Date all `Z` (or `Z/D`, whose first alternative is
        // `Z`). This preset used to special-case Patient's Name and Patient
        // ID to a visible "Anonymous" dummy value purely to keep an older
        // version of this test passing, even though DICOMAnonymizer had no
        // "present but empty" primitive at the time. Now that it does, all
        // four attributes get the same, standards-correct treatment: present
        // and zero-length, not removed and not replaced with dummy text.
        let dataset = DICOMDataset(elements: [
            DICOMElement(tag: .patientName, vr: .PN, value: Data("Doe^Jane".utf8)),
            DICOMElement(tag: patientID, vr: .LO, value: Data("PAT-42".utf8)),
            DICOMElement(tag: accessionNumber, vr: .SH, value: Data("ACC-9".utf8)),
            DICOMElement(tag: patientBirthDate, vr: .DA, value: Data("19700101".utf8))
        ])

        let result = DICOMDeidentificationProfile.basicApplicationLevelConfidentiality().anonymize(dataset)

        #expect(result[.patientName] == DICOMElement(tag: .patientName, vr: .PN, value: Data()))
        #expect(result[patientID] == DICOMElement(tag: patientID, vr: .LO, value: Data()))
        #expect(result[accessionNumber] == DICOMElement(tag: accessionNumber, vr: .SH, value: Data()))
        #expect(result[patientBirthDate] == DICOMElement(tag: patientBirthDate, vr: .DA, value: Data()))
    }
}

/// Tests for burned-in annotation handling: pixel data can carry
/// identifiers as rendered text that no attribute-table action touches, so
/// `DICOMConfidentialityProfile.deidentify` refuses to proceed when
/// `(0028,0301)` declares that annotation is present, and surfaces a
/// warning (rather than staying silent) when the attribute is absent.
struct DICOMBurnedInAnnotationTests {
    private let burnedInAnnotation = DICOMTag(group: 0x0028, element: 0x0301)

    private func file(burnedIn value: String?) throws -> DICOMFile {
        var elements = [
            DICOMElement(tag: .sopClassUID, vr: .UI, value: Data("1.2.840.10008.5.1.4.1.1.7".utf8)),
            DICOMElement(tag: .sopInstanceUID, vr: .UI, value: Data("1.2.3".utf8))
        ]
        if let value {
            elements.append(DICOMElement(tag: burnedInAnnotation, vr: .CS, value: Data(value.utf8)))
        }
        return try DICOMFile(data: DICOMWriter.write(dataset: DICOMDataset(elements: elements)))
    }

    @Test func fileDeclaringBurnedInAnnotationYesReportsDeclaredPresent() throws {
        let file = try file(burnedIn: "YES")

        #expect(file.burnedInAnnotation == .declaredPresent)
    }

    @Test func fileDeclaringBurnedInAnnotationNoReportsDeclaredAbsent() throws {
        let file = try file(burnedIn: "NO")

        #expect(file.burnedInAnnotation == .declaredAbsent)
    }

    @Test func fileWithNoBurnedInAnnotationAttributeReportsUndeclared() throws {
        let file = try file(burnedIn: nil)

        #expect(file.burnedInAnnotation == .undeclared)
    }

    @Test func deidentifyThrowsWhenBurnedInAnnotationIsDeclaredPresent() throws {
        let file = try file(burnedIn: "YES")
        let profile = DICOMConfidentialityProfile()

        #expect(throws: DICOMError.burnedInAnnotationPresent) {
            try profile.deidentify(file, replacement: "Anonymous")
        }
    }

    @Test func deidentifySucceedsWithNoWarningWhenBurnedInAnnotationIsDeclaredAbsent() throws {
        let file = try file(burnedIn: "NO")
        let profile = DICOMConfidentialityProfile()

        let result = try profile.deidentify(file, replacement: "Anonymous")

        #expect(result.warnings.isEmpty)
    }

    @Test func deidentifySucceedsWithWarningWhenBurnedInAnnotationIsUndeclared() throws {
        let file = try file(burnedIn: nil)
        let profile = DICOMConfidentialityProfile()

        let result = try profile.deidentify(file, replacement: "Anonymous")

        #expect(result.warnings.isEmpty == false)
    }
}

/// Tests for recording what was applied (PS3.15 E.1.1): a de-identification
/// claim is only meaningful if `deidentify` stamps Patient Identity Removed,
/// De-identification Method, and De-identification Method Code Sequence
/// into its output.
struct DICOMDeidentificationMethodRecordingTests {
    private let patientIdentityRemoved = DICOMTag(group: 0x0012, element: 0x0062)
    private let deidentificationMethod = DICOMTag(group: 0x0012, element: 0x0063)
    private let deidentificationMethodCodeSequence = DICOMTag(group: 0x0012, element: 0x0064)
    private let codeValue = DICOMTag(group: 0x0008, element: 0x0100)

    private func file() throws -> DICOMFile {
        try DICOMFile(data: DICOMWriter.write(dataset: DICOMDataset(elements: [
            DICOMElement(tag: .sopClassUID, vr: .UI, value: Data("1.2.840.10008.5.1.4.1.1.7".utf8)),
            DICOMElement(tag: .sopInstanceUID, vr: .UI, value: Data("1.2.3".utf8)),
            DICOMElement(tag: DICOMTag(group: 0x0028, element: 0x0301), vr: .CS, value: Data("NO".utf8))
        ])))
    }

    private func codeValues(_ dataset: DICOMDataset) -> Set<String> {
        Set((dataset[deidentificationMethodCodeSequence]?.sequenceItems ?? []).compactMap { $0[codeValue]?.stringValue })
    }

    @Test func recordsPatientIdentityRemovedAndBasicProfileCodeWithNoOptionsSelected() throws {
        let result = try DICOMConfidentialityProfile().deidentify(try file(), replacement: "Anonymous")

        #expect(result.dataset[patientIdentityRemoved]?.stringValue == "YES")
        #expect(result.dataset[deidentificationMethod]?.stringValue?.isEmpty == false)
        #expect(codeValues(result.dataset) == ["113100"])
    }

    @Test func selectingRetainUIDsAddsItsCode() throws {
        let profile = DICOMConfidentialityProfile(options: [.retainUIDs])

        let result = try profile.deidentify(try file(), replacement: "Anonymous")

        #expect(codeValues(result.dataset).contains("113110"))
    }

    @Test func unselectedOptionCodesDoNotAppear() throws {
        let profile = DICOMConfidentialityProfile(options: [.retainUIDs])

        let result = try profile.deidentify(try file(), replacement: "Anonymous")

        // Only the Basic Profile code and Retain UIDs' code should appear —
        // no other option's code, even though several other options exist.
        #expect(codeValues(result.dataset) == ["113100", "113110"])
    }
}
