import Foundation
import Testing
@testable import DICOMKit

/// Tests for the PS3.15 Table E.1-1 generated confidentiality table.
///
/// `DICOMDeidentificationTable` is internal and generated by
/// `Tools/generate_deidentification_profile.py`; these tests exercise it
/// directly to keep the generator honest before the public
/// `DICOMConfidentialityProfile` model is layered on top of it.
struct DICOMDeidentificationTableTests {
    @Test func generatesExpectedNumberOfEntries() {
        // Table E.1-1 (2025a) has 631 attribute rows: 627 exact tags, 3
        // repeating-group ("xx") tags, and 1 dropped "Private Attributes"
        // placeholder row that isn't a concrete or maskable tag.
        #expect(DICOMDeidentificationTable.entries.count == 627)
        #expect(DICOMDeidentificationTable.maskedEntries.count == 3)
    }

    @Test func patientNameIsReplacedWithZeroLengthUnderBasicProfile() {
        let entry = DICOMDeidentificationTable.entries[.patientName]

        #expect(entry?.basic == "Z")
        #expect(entry?.overrides.isEmpty == true)
    }

    @Test func accessionNumberIsReplacedWithZeroLengthUnderBasicProfile() {
        let entry = DICOMDeidentificationTable.entries[DICOMTag(group: 0x0008, element: 0x0050)]

        #expect(entry?.basic == "Z")
    }

    @Test func acquisitionCommentsIsRemovedWithCleanDescriptorOverride() {
        let entry = DICOMDeidentificationTable.entries[DICOMTag(group: 0x0018, element: 0x4000)]

        #expect(entry?.basic == "X")
        // Column index 7 = Clean Desc. Opt.
        #expect(entry?.overrides[7] == "C")
    }

    @Test func studyInstanceUIDIsRemappedWithRetainUIDsOverride() {
        let entry = DICOMDeidentificationTable.entries[.studyInstanceUID]

        #expect(entry?.basic == "U")
        // Column index 1 = Rtn. UIDs Opt.
        #expect(entry?.overrides[1] == "K")
    }

    @Test func repeatingGroupTagsAreMaskedRatherThanDropped() {
        // Curve Data (50xx,xxxx): Basic Profile X.
        let curveData = DICOMTag(group: 0x5012, element: 0x1234)
        let match = DICOMDeidentificationTable.maskedEntries.first { $0.matches(curveData) }

        #expect(match?.basic == "X")
        // Column index 9 = Clean Graph. Opt.
        #expect(match?.overrides[9] == "C")

        // Overlay Comments (60xx,4000) and Overlay Data (60xx,3000) also match by group mask only on their fixed element.
        #expect(DICOMDeidentificationTable.maskedEntries.contains { $0.matches(DICOMTag(group: 0x6010, element: 0x4000)) })
        #expect(DICOMDeidentificationTable.maskedEntries.contains { $0.matches(DICOMTag(group: 0x6010, element: 0x3000)) })
        #expect(DICOMDeidentificationTable.maskedEntries.contains { $0.matches(DICOMTag(group: 0x6010, element: 0x0010)) } == false)
    }
}
