import Foundation
import Testing
@testable import DICOMKit

/// Tests for the PS3.15 Table E.1-1 generated confidentiality table.
///
/// `DICOMDeidentificationTable` is internal and generated by
/// `Tools/generate_deidentification_profile.py`; these tests exercise it
/// directly to keep the generator honest before the public
/// `DICOMConfidentialityProfile` model is layered on top of it.
struct DICOMDeidentificationTableTests {
    @Test func generatesExpectedNumberOfEntries() {
        // Table E.1-1 (2025a) has 631 attribute rows: 627 exact tags, 3
        // repeating-group ("xx") tags, and 1 dropped "Private Attributes"
        // placeholder row that isn't a concrete or maskable tag.
        #expect(DICOMDeidentificationTable.entries.count == 627)
        #expect(DICOMDeidentificationTable.maskedEntries.count == 3)
    }

    @Test func patientNameIsReplacedWithZeroLengthUnderBasicProfile() {
        let entry = DICOMDeidentificationTable.entries[.patientName]

        #expect(entry?.basic == "Z")
        #expect(entry?.overrides.isEmpty == true)
    }

    @Test func accessionNumberIsReplacedWithZeroLengthUnderBasicProfile() {
        let entry = DICOMDeidentificationTable.entries[DICOMTag(group: 0x0008, element: 0x0050)]

        #expect(entry?.basic == "Z")
    }

    @Test func acquisitionCommentsIsRemovedWithCleanDescriptorOverride() {
        let entry = DICOMDeidentificationTable.entries[DICOMTag(group: 0x0018, element: 0x4000)]

        #expect(entry?.basic == "X")
        // Column index 7 = Clean Desc. Opt.
        #expect(entry?.overrides[7] == "C")
    }

    @Test func studyInstanceUIDIsRemappedWithRetainUIDsOverride() {
        let entry = DICOMDeidentificationTable.entries[.studyInstanceUID]

        #expect(entry?.basic == "U")
        // Column index 1 = Rtn. UIDs Opt.
        #expect(entry?.overrides[1] == "K")
    }

    @Test func repeatingGroupTagsAreMaskedRatherThanDropped() {
        // Curve Data (50xx,xxxx): Basic Profile X.
        let curveData = DICOMTag(group: 0x5012, element: 0x1234)
        let match = DICOMDeidentificationTable.maskedEntries.first { $0.matches(curveData) }

        #expect(match?.basic == "X")
        // Column index 9 = Clean Graph. Opt.
        #expect(match?.overrides[9] == "C")

        // Overlay Comments (60xx,4000) and Overlay Data (60xx,3000) also match by group mask only on their fixed element.
        #expect(DICOMDeidentificationTable.maskedEntries.contains { $0.matches(DICOMTag(group: 0x6010, element: 0x4000)) })
        #expect(DICOMDeidentificationTable.maskedEntries.contains { $0.matches(DICOMTag(group: 0x6010, element: 0x3000)) })
        #expect(DICOMDeidentificationTable.maskedEntries.contains { $0.matches(DICOMTag(group: 0x6010, element: 0x0010)) } == false)
    }
}

/// Tests for the public `DICOMConfidentialityProfile` model built on top of
/// `DICOMDeidentificationTable`.
struct DICOMConfidentialityProfileTests {
    private let accessionNumber = DICOMTag(group: 0x0008, element: 0x0050)
    private let acquisitionComments = DICOMTag(group: 0x0018, element: 0x4000)
    private let patientID = DICOMTag(group: 0x0010, element: 0x0020)
    private let patientSex = DICOMTag(group: 0x0010, element: 0x0040)
    private let patientBirthDate = DICOMTag(group: 0x0010, element: 0x0030)
    private let contentDate = DICOMTag(group: 0x0008, element: 0x0023)
    private let attributeModificationDateTime = DICOMTag(group: 0x0400, element: 0x0562)
    private let rows = DICOMTag(group: 0x0028, element: 0x0010)
    private let columns = DICOMTag(group: 0x0028, element: 0x0011)

    @Test func basicProfileAloneResolvesRepresentativeAttributesToRemoveOrBlank() {
        let profile = DICOMConfidentialityProfile()

        #expect(profile.action(for: .patientName) == .replaceWithZeroLength)
        #expect(profile.action(for: accessionNumber) == .replaceWithZeroLength)
        #expect(profile.action(for: acquisitionComments) == .remove)

        // makeAnonymizer collapses both Z and X down to an actual removal,
        // since DICOMAnonymizer has no "present but forced empty" primitive.
        let dataset = DICOMDataset(elements: [
            DICOMElement(tag: .patientName, vr: .PN, value: Data("Doe^Jane".utf8)),
            DICOMElement(tag: accessionNumber, vr: .SH, value: Data("ACC-1".utf8)),
            DICOMElement(tag: acquisitionComments, vr: .LT, value: Data("comment".utf8))
        ])
        let result = profile.makeAnonymizer(replacement: "Anonymous").anonymize(dataset)

        #expect(result[.patientName] == nil)
        #expect(result[accessionNumber] == nil)
        #expect(result[acquisitionComments] == nil)
    }

    @Test func retainUIDsOptionKeepsStudyInstanceUIDWhereBareProfileRemaps() {
        let bare = DICOMConfidentialityProfile()
        let retainUIDs = DICOMConfidentialityProfile(options: [.retainUIDs])

        #expect(bare.action(for: .studyInstanceUID) == .replaceUID)
        #expect(retainUIDs.action(for: .studyInstanceUID) == .keep)
    }

    @Test func retainPatientCharacteristicsOptionKeepsPatientSex() {
        let bare = DICOMConfidentialityProfile()
        let retainCharacteristics = DICOMConfidentialityProfile(options: [.retainPatientCharacteristics])

        #expect(bare.action(for: patientSex) == .replaceWithZeroLength)
        #expect(retainCharacteristics.action(for: patientSex) == .keep)
    }

    @Test func attributeAbsentFromTableReturnsNilSoCallerKeepsIt() {
        let profile = DICOMConfidentialityProfile()

        #expect(profile.action(for: rows) == nil)
        #expect(profile.action(for: columns) == nil)
    }

    @Test func laterOptionColumnWinsWhenTwoSelectedOptionsOverrideTheSameAttribute() {
        // Content Date has both a Retain Longitudinal Full Dates override
        // (K) and a Retain Longitudinal Modified Dates override (C).
        // Selecting both is documented to resolve to the later column,
        // i.e. Clean (C), not Keep (K).
        let both = DICOMConfidentialityProfile(options: [.retainLongitudinalFullDates, .retainLongitudinalModifiedDates])

        #expect(both.action(for: contentDate) == .clean)
    }

    @Test func makeAnonymizerReplacesDummyCodedAttributesWithTheReplacementText() {
        let profile = DICOMConfidentialityProfile()
        let dataset = DICOMDataset(elements: [
            DICOMElement(tag: attributeModificationDateTime, vr: .DT, value: Data("20240101".utf8))
        ])

        let result = profile.makeAnonymizer(replacement: "REDACTED").anonymize(dataset)

        #expect(result[attributeModificationDateTime]?.stringValue == "REDACTED")
    }

    @Test func basicApplicationLevelConfidentialityStillReplacesDirectPatientIdentifiersWithDummyText() {
        let dataset = DICOMDataset(elements: [
            DICOMElement(tag: .patientName, vr: .PN, value: Data("Doe^Jane".utf8)),
            DICOMElement(tag: patientID, vr: .LO, value: Data("PAT-42".utf8)),
            DICOMElement(tag: accessionNumber, vr: .SH, value: Data("ACC-9".utf8)),
            DICOMElement(tag: patientBirthDate, vr: .DA, value: Data("19700101".utf8))
        ])

        let result = DICOMDeidentificationProfile.basicApplicationLevelConfidentiality().anonymize(dataset)

        #expect(result[.patientName]?.stringValue == "Anonymous")
        #expect(result[patientID]?.stringValue == "Anonymous")
        #expect(result[accessionNumber] == nil)
        #expect(result[patientBirthDate] == nil)
    }
}

/// Tests for burned-in annotation handling: pixel data can carry
/// identifiers as rendered text that no attribute-table action touches, so
/// `DICOMConfidentialityProfile.deidentify` refuses to proceed when
/// `(0028,0301)` declares that annotation is present, and surfaces a
/// warning (rather than staying silent) when the attribute is absent.
struct DICOMBurnedInAnnotationTests {
    private let burnedInAnnotation = DICOMTag(group: 0x0028, element: 0x0301)

    private func file(burnedIn value: String?) throws -> DICOMFile {
        var elements = [
            DICOMElement(tag: .sopClassUID, vr: .UI, value: Data("1.2.840.10008.5.1.4.1.1.7".utf8)),
            DICOMElement(tag: .sopInstanceUID, vr: .UI, value: Data("1.2.3".utf8))
        ]
        if let value {
            elements.append(DICOMElement(tag: burnedInAnnotation, vr: .CS, value: Data(value.utf8)))
        }
        return try DICOMFile(data: DICOMWriter.write(dataset: DICOMDataset(elements: elements)))
    }

    @Test func fileDeclaringBurnedInAnnotationYesReportsDeclaredPresent() throws {
        let file = try file(burnedIn: "YES")

        #expect(file.burnedInAnnotation == .declaredPresent)
    }

    @Test func fileDeclaringBurnedInAnnotationNoReportsDeclaredAbsent() throws {
        let file = try file(burnedIn: "NO")

        #expect(file.burnedInAnnotation == .declaredAbsent)
    }

    @Test func fileWithNoBurnedInAnnotationAttributeReportsUndeclared() throws {
        let file = try file(burnedIn: nil)

        #expect(file.burnedInAnnotation == .undeclared)
    }

    @Test func deidentifyThrowsWhenBurnedInAnnotationIsDeclaredPresent() throws {
        let file = try file(burnedIn: "YES")
        let profile = DICOMConfidentialityProfile()

        #expect(throws: DICOMError.burnedInAnnotationPresent) {
            try profile.deidentify(file, replacement: "Anonymous")
        }
    }

    @Test func deidentifySucceedsWithNoWarningWhenBurnedInAnnotationIsDeclaredAbsent() throws {
        let file = try file(burnedIn: "NO")
        let profile = DICOMConfidentialityProfile()

        let result = try profile.deidentify(file, replacement: "Anonymous")

        #expect(result.warnings.isEmpty)
    }

    @Test func deidentifySucceedsWithWarningWhenBurnedInAnnotationIsUndeclared() throws {
        let file = try file(burnedIn: nil)
        let profile = DICOMConfidentialityProfile()

        let result = try profile.deidentify(file, replacement: "Anonymous")

        #expect(result.warnings.isEmpty == false)
    }
}
